/****************************************************************

  Generated by Vortex DDS IDL to C Translator
  File name: bit.c
  Source: bit.idl
  Generated: Sun Jan 21 18:34:03 CET 2018
  Vortex DDS: V0.1.0

*****************************************************************/
#include "bit.h"


static const dds_key_descriptor_t dds_bit_SKeyBValue_keys[1] =
{
  { "key", 0 }
};

static const uint32_t dds_bit_SKeyBValue_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_STR | DDS_OP_FLAG_KEY, offsetof (dds_bit_SKeyBValue, key),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (dds_bit_SKeyBValue, value),
  DDS_OP_RTS
};

const dds_topic_descriptor_t dds_bit_SKeyBValue_desc =
{
  sizeof (dds_bit_SKeyBValue),
  sizeof (char *),
  DDS_TOPIC_NO_OPTIMIZE,
  1u,
  "dds::bit::SKeyBValue",
  dds_bit_SKeyBValue_keys,
  3,
  dds_bit_SKeyBValue_ops,
  "<MetaData version=\"1.0.0\"><Module name=\"dds\"><Module name=\"bit\"><TypeDef name=\"bytes\"><Sequence><Octet/></Sequence></TypeDef><Struct name=\"SKeyBValue\"><Member name=\"key\"><String/></Member><Member name=\"value\"><Type name=\"bytes\"/></Member></Struct></Module></Module></MetaData>"
};


static const dds_key_descriptor_t dds_bit_IKeyBValue_keys[1] =
{
  { "key", 0 }
};

static const uint32_t dds_bit_IKeyBValue_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_KEY, offsetof (dds_bit_IKeyBValue, key),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (dds_bit_IKeyBValue, value),
  DDS_OP_RTS
};

const dds_topic_descriptor_t dds_bit_IKeyBValue_desc =
{
  sizeof (dds_bit_IKeyBValue),
  sizeof (char *),
  DDS_TOPIC_FIXED_KEY | DDS_TOPIC_NO_OPTIMIZE,
  1u,
  "dds::bit::IKeyBValue",
  dds_bit_IKeyBValue_keys,
  3,
  dds_bit_IKeyBValue_ops,
  "<MetaData version=\"1.0.0\"><Module name=\"dds\"><Module name=\"bit\"><TypeDef name=\"bytes\"><Sequence><Octet/></Sequence></TypeDef><Struct name=\"IKeyBValue\"><Member name=\"key\"><Long/></Member><Member name=\"value\"><Type name=\"bytes\"/></Member></Struct></Module></Module></MetaData>"
};


static const dds_key_descriptor_t dds_bit_IKeySValue_keys[1] =
{
  { "key", 0 }
};

static const uint32_t dds_bit_IKeySValue_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_KEY, offsetof (dds_bit_IKeySValue, key),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (dds_bit_IKeySValue, value),
  DDS_OP_RTS
};

const dds_topic_descriptor_t dds_bit_IKeySValue_desc =
{
  sizeof (dds_bit_IKeySValue),
  sizeof (char *),
  DDS_TOPIC_FIXED_KEY | DDS_TOPIC_NO_OPTIMIZE,
  1u,
  "dds::bit::IKeySValue",
  dds_bit_IKeySValue_keys,
  3,
  dds_bit_IKeySValue_ops,
  "<MetaData version=\"1.0.0\"><Module name=\"dds\"><Module name=\"bit\"><Struct name=\"IKeySValue\"><Member name=\"key\"><Long/></Member><Member name=\"value\"><String/></Member></Struct></Module></Module></MetaData>"
};


static const dds_key_descriptor_t dds_bit_SKeySValue_keys[1] =
{
  { "key", 0 }
};

static const uint32_t dds_bit_SKeySValue_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_STR | DDS_OP_FLAG_KEY, offsetof (dds_bit_SKeySValue, key),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (dds_bit_SKeySValue, value),
  DDS_OP_RTS
};

const dds_topic_descriptor_t dds_bit_SKeySValue_desc =
{
  sizeof (dds_bit_SKeySValue),
  sizeof (char *),
  DDS_TOPIC_NO_OPTIMIZE,
  1u,
  "dds::bit::SKeySValue",
  dds_bit_SKeySValue_keys,
  3,
  dds_bit_SKeySValue_ops,
  "<MetaData version=\"1.0.0\"><Module name=\"dds\"><Module name=\"bit\"><Struct name=\"SKeySValue\"><Member name=\"key\"><String/></Member><Member name=\"value\"><String/></Member></Struct></Module></Module></MetaData>"
};


static const uint32_t dds_bit_SValue_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (dds_bit_SValue, value),
  DDS_OP_RTS
};

const dds_topic_descriptor_t dds_bit_SValue_desc =
{
  sizeof (dds_bit_SValue),
  sizeof (char *),
  DDS_TOPIC_NO_OPTIMIZE,
  0u,
  "dds::bit::SValue",
  NULL,
  2,
  dds_bit_SValue_ops,
  "<MetaData version=\"1.0.0\"><Module name=\"dds\"><Module name=\"bit\"><Struct name=\"SValue\"><Member name=\"value\"><String/></Member></Struct></Module></Module></MetaData>"
};
